import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  LibraryBig,
  Loader2,
  LogIn,
  LucideIcon,
  LucideShoppingBag,
  Moon,
  MoreVertical,
  Music2,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  UserCircle2Icon,
  UserPen,
  UserX2Icon,
  X,
} from 'lucide-react';

export * from 'lucide-react';

export { PlusCircledIcon, Cross2Icon } from '@radix-ui/react-icons';

export type Icon = LucideIcon;

export const DashboardNavIcons = {
  add: Plus,
  arrowRight: ArrowRight,
  billing: CreditCard,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  close: X,
  dashboard: LayoutDashboardIcon,
  ellipsis: MoreVertical,
  employee: UserX2Icon,
  help: HelpCircle,
  kanban: CircuitBoardIcon,
  laptop: Laptop,
  library: LibraryBig,
  login: LogIn,
  logo: Command,
  media: Image,
  music: Music2,
  moon: Moon,
  page: File,
  pizza: Pizza,
  post: FileText,
  product: LucideShoppingBag,
  settings: Settings,
  spinner: Loader2,
  sun: SunMedium,
  trash: Trash,
  user2: UserCircle2Icon,
  user: User,
  userPen: UserPen,
  warning: AlertTriangle,
};